version: "2"
services:
  chatroulette:
    image: "node:17"
    user: "node"
    stdin_open: true
    tty: true
    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=test
    volumes:
      - /srv/chatroulette/app:/home/node/app
    ports:
      - 3000:3000
    command: bash -c "npm i && npm update && npm run build && npm start"
